This project requires termbox-go.
If you have not previously installed termbox-go you will get an error when you attempt to install the project.

```
$ go get github.com/asciimoo/wuzz
# github.com/jroimartin/gocui
../../.gocode/src/github.com/jroimartin/gocui/keybinding.go:74: undefined: termbox.MouseRelease
```

Informing the user they need termbox-go would be helpful so I have included it in the readme.